name: Create Release
on: create

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref_type == 'tag' && contains(github.ref, 'RC') }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: python -m pip install -r ${{ github.workspace }}/scripts/release/requirements.txt

      - name: Test
        run: echo "${{ github.event.ref }}" "${{ github.ref }}"
